---
- name: Provision the ISO images to autoinstall pve
  hosts: localhost
  tasks:
    - name: Ensure the pve directories exist
      ansible.builtin.file:
        path: "/tmp/pve/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - iso
        - answers
        - output

    - name: Ensure the pve answer directories exist
      ansible.builtin.file:
        path: "/tmp/pve/answers/{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ groups['pves'] }}"

    - name: Create the answer files
      ansible.builtin.template:
        src: 'templates/{{ env }}/answer.toml.j2'
        dest: '/tmp/pve/answers/{{ item }}/answer.toml'
        mode: '0644'
      loop: "{{ groups['pves'] }}"
      vars:
        pve_ssh_key: "{{ lookup('file', '/home/{{ pve.ssh_key_user }}/.ssh/id_ed25519.pub') }}"

    - name: Download the Proxmox VE ISO
      ansible.builtin.get_url:
        url: https://enterprise.proxmox.com/iso/proxmox-ve_8.4-1.iso
        dest: /tmp/pve/iso/pve.iso
        mode: '0644'

    - name: Build the custom ISO with the autoinstall assistant
      containers.podman.podman_image:
        name: proxmox-auto-installer
        path: proxmox-auto-installer-docker

    - name: Run container
      containers.podman.podman_container:
        name: '{{ item }}-installer'
        image: localhost/proxmox-auto-installer
        command: /iso/pve.iso {{ item }}
        volumes:
          - /tmp/pve/iso:/iso:ro
          - /tmp/pve/answers:/answers:ro
          - /tmp/pve/output:/out
        state: started
        rm: true
      loop: "{{ groups['pves'] }}"

    - name: Run Terraform to create test VMs with custom ISO
      when: env == 'test'
      block:
        - name: Create terraform tfvars file
          ansible.builtin.template:
            src: templates/terraform.tfvars.j2
            dest: terraform/terraform.tfvars
            mode: '0644'

        - name: Apply Terraform configuration
          community.general.terraform:
            project_path: "{{ playbook_dir }}/terraform"
            state: present
            force_init: true
            variables:
              pve_iso_path: '/tmp'
