---
- name: Configure VM cluster load balancers
  hosts: lbs
  become: true
  tasks:
    - name: Ensure the machine hostname matches the inventory
      ansible.builtin.command: hostnamectl set-hostname '{{ inventory_hostname }}'
      register: output
      changed_when: output.rc != 0

    - name: Install apt packages
      ansible.builtin.apt:
        name:
          - sudo
          - haproxy
          - keepalived
        state: present
        update_cache: true

    - name: Create the haproxy config file
      ansible.builtin.template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'

    - name: Create the keepalived config file
      ansible.builtin.template:
        src: templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        mode: '0644'

    - name: Restart services
      ansible.builtin.systemd_service:
        name: '{{ item }}'
        state: restarted
      loop:
        - haproxy
        - keepalived

- name: Configure VM nodes
  hosts: nodes
  become: true
  tasks:
    - name: Ensure the machine hostname matches the inventory
      ansible.builtin.command: hostnamectl set-hostname '{{ inventory_hostname }}'
      register: output
      changed_when: output.rc != 0

    - name: Install apt packages
      ansible.builtin.apt:
        name:
          - sudo
          - curl
          - git
          - nfs-common
          - open-iscsi
          - python3-pip
        state: present
        update_cache: true

    - name: Install pip packages
      ansible.builtin.pip:
        name:
          - kubernetes
        state: present
        break_system_packages: true

    - name: Enable the service iscsid
      ansible.builtin.systemd_service:
        name: iscsid
        enabled: true
        state: started
        masked: false

    - name: Download k3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: "/tmp/install_k3s.sh"
        mode: '0770'

- name: Install k3s and configure CNI on the main control plane node
  hosts: c01
  become: true
  tasks:
    - name: Install k3s on the main control plane node
      ansible.builtin.command: sh /tmp/install_k3s.sh
      environment:
        INSTALL_K3S_VERSION: '{{ k3s_version }}'
        INSTALL_K3S_EXEC: |
          "server --cluster-init --tls-san={{ cluster_ha_vip }} --token {{ node.k3s_token }} \
          --flannel-backend=none --disable-network-policy --disable-kube-proxy --disable=traefik --disable=servicelb"
      register: output
      changed_when: output.rc != 0

    - name: Deploy the CNI
      block:
        - name: Checkout the homelab repo
          ansible.builtin.git:
            repo: https://github.com/msdeleyto/homelab-manifests.git
            dest: /tmp/homelab
            single_branch: true
            version: main

        - name: Deploy
          ansible.builtin.shell: /tmp/homelab/network/tooling/bootstrap
          args:
            executable: /bin/bash
          environment:
            INFRA_DOMAIN: '{{ cluster.secrets.infra.domain }}'
            INFRA_LB_IP: '{{ cluster.secrets.infra.lb_ip }}'
            INFRA_HA_VIP: '{{ cluster.secrets.infra.ha_vip }}'
          register: output
          changed_when: output.rc != 0
      always:
        - name: Remove the homelab directory
          ansible.builtin.file:
            path: /tmp/homelab
            state: absent

- name: Install k3s on the control plane nodes
  hosts: cp_nodes
  become: true
  tasks:
    - name: Install k3s on the other control plane nodes
      ansible.builtin.command: sh /tmp/install_k3s.sh
      environment:
        INSTALL_K3S_VERSION: '{{ k3s_version }}'
        INSTALL_K3S_EXEC: |
          "server --token {{ node.k3s_token }} --server=https://{{ cluster_ha_vip }}:6443 --tls-san={{ cluster_ha_vip }} \
          --flannel-backend=none --disable-network-policy --disable-kube-proxy --disable=traefik"
      when: inventory_hostname != 'c01'
      register: output
      changed_when: output.rc != 0

- name: Register the control plane token
  hosts: localhost
  tasks:
    - name: Register the control plane token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/token
      delegate_to: c01
      become: true
      register: cp_token

- name: Install k3s on the worker nodes
  hosts: worker_nodes
  become: true
  tasks:
    - name: Install k3s on the worker node
      ansible.builtin.command: sh /tmp/install_k3s.sh
      environment:
        INSTALL_K3S_VERSION: '{{ k3s_version }}'
        INSTALL_K3S_EXEC: "agent --server=https://{{ cluster_ha_vip }}:6443 --token={{ hostvars['localhost'].cp_token.content | b64decode }}"
      register: output
      changed_when: output.rc != 0

- name: Configure k8s cluster
  hosts: c01
  become: true
  tasks:
    - name: Set node labels
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item }}"
            labels:
              role: "{{ hostvars[item].role }}"
      loop: "{{ groups['nodes'] }}"

    - name: Taint control plane nodes
      kubernetes.core.k8s_taint:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        state: present
        name: "{{ item }}"
        taints:
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
      loop: "{{ groups['cp_nodes'] }}"

- name: Create snapshots of the VMs configured
  hosts: localhost
  tasks:
    - name: Delete previous snapshot VM
      community.proxmox.proxmox_snap:
        api_user: root@pam
        api_password: '{{ pve.root_password }}'
        api_host: "{{ hostvars[hostvars[item]['proxmox_node']]['ansible_host'] }}"
        hostname: "{{ item }}"
        state: absent
        snapname: "snapshot-{{ item }}"
      loop: "{{ groups['vms'] }}"

    - name: Create snapshot of the VM
      community.proxmox.proxmox_snap:
        api_user: root@pam
        api_password: '{{ pve.root_password }}'
        api_host: "{{ hostvars[hostvars[item]['proxmox_node']]['ansible_host'] }}"
        hostname: "{{ item }}"
        state: present
        snapname: "snapshot-{{ item }}"
        retention: 1
      loop: "{{ groups['vms'] }}"

- name: Pull cluster files to grant local access
  hosts: c01
  become: true
  tasks:
    - name: Transfer the cluster's certificate authority to localhost
      ansible.builtin.fetch:
        src: /var/lib/rancher/k3s/server/tls/server-ca.crt
        dest: "{{ lookup('env', 'HOME') }}/.kube/{{ env }}/ca.crt"
        flat: true

    - name: Transfer the cluster's admin user client certificate to localhost
      ansible.builtin.fetch:
        src: /var/lib/rancher/k3s/server/tls/client-admin.crt
        dest: "{{ lookup('env', 'HOME') }}/.kube/{{ env }}/admin.crt"
        flat: true

    - name: Transfer the cluster's admin user client key to localhost
      ansible.builtin.fetch:
        src: /var/lib/rancher/k3s/server/tls/client-admin.key
        dest: "{{ lookup('env', 'HOME') }}/.kube/{{ env }}/admin.key"
        flat: true

- name: Set kubectl context for the new cluster
  hosts: localhost
  tasks:
    - name: Set kubectl cluster entry for the new cluster
      ansible.builtin.command: |
        kubectl config set-cluster {{ env }}-cluster \
          --server=https://{{ cluster_ha_vip }}:6443 \
          --certificate-authority={{ lookup('env', 'HOME') }}/.kube/{{ env }}/ca.crt \
          --embed-certs=true
      register: output
      changed_when: output.rc == 0

    - name: Set kubectl admin credentials for the new cluster
      ansible.builtin.command: |
        kubectl config set-credentials {{ env }}-admin \
          --client-certificate={{ lookup('env', 'HOME') }}/.kube/{{ env }}/admin.crt \
          --client-key={{ lookup('env', 'HOME') }}/.kube/{{ env }}/admin.key \
          --embed-certs=true
      register: output
      changed_when: output.rc == 0

    - name: Create kubectl context
      ansible.builtin.command: "kubectl config set-context {{ env }} --cluster={{ env }}-cluster --user={{ env }}-admin"
      register: output
      changed_when: output.rc == 0

    - name: Use the new context
      ansible.builtin.command: "kubectl config use-context {{ env }}"
      register: output
      changed_when: output.rc == 0

- name: Install cilium cli
  hosts: localhost
  tasks:
    - name: Download cilium cli
      ansible.builtin.get_url:
        url: https://github.com/cilium/cilium-cli/releases/download/v0.19.0/cilium-linux-amd64.tar.gz
        dest: /tmp/cilium-linux-amd64.tar.gz
        mode: '0770'

    - name: Download cilium cli checksum
      ansible.builtin.get_url:
        url: https://github.com/cilium/cilium-cli/releases/download/v0.19.0/cilium-linux-amd64.tar.gz.sha256sum
        dest: /tmp/cilium-linux.tar.gz.sha256sum
        mode: '0770'

    - name: Verify cilium
      ansible.builtin.command: sha256sum --check cilium-linux.tar.gz.sha256sum
      args:
        chdir: /tmp
      register: output
      changed_when: output.rc != 0

    - name: Extract cilium
      ansible.builtin.unarchive:
        src: /tmp/cilium-linux-amd64.tar.gz
        dest: "{{ lookup('env', 'HOME') }}/.local/bin"
